sim_par<-function(N=20,eprob=0.1,phiv=0.1,PrEP1=0.1,PrEP2=0.2, p1=0.2,p2=0.1, nsim=1000, scen="all"){
  res<-foreach(icount(nsim), .combine=rbind) %dopar%{
    # plot a random graph, 3 color options
    #control scenario graph, 10% assignment prob
    g <- sample_gnp(N,eprob)
    vertex_attr(g) <- list(color =c(rep("red", gorder(g)*phiv), rep("blue",gorder(g)*PrEP1), rep("black", gorder(g)*(1-(phiv+PrEP1)))))
    df_g<-as_long_data_frame(g)
    colnames(df_g)<-c("from","to","color1","color2")
    #compute P(HIV|PrEP)
    treat_g<-subset(df_g, (df_g$color1=="blue"|df_g$color2=="blue"))
    treat_inf_contact_g<-subset(treat_g, treat_g$color1=="red"|treat_g$color2=="red")
    hiv_given_prep_g<-ifelse(nrow(treat_g)!=0,(nrow(treat_inf_contact_g)*p2)/nrow(treat_g),0)
    #Compute P(HIV|-PrEP)
    no_treat_g<-subset(df_g, df_g$color1!="blue"&df_g$color2!="blue")
    no_treat_inf_contact_g<-subset(no_treat_g, no_treat_g$color1=="red"|no_treat_g$color2=="red")
    hiv_given_no_prep_g<-ifelse(nrow(no_treat_g)!=0,(nrow(no_treat_inf_contact_g)*p1)/nrow(no_treat_g),0)
    #Randomly assign 20% overall (shuffle attributes)
    h<-set_vertex_attr(g,"color",value=gtools::permute(c(rep("red", gorder(g)*phiv), rep("blue",gorder(g)*PrEP2), rep("black", gorder(g)*(1-(phiv+PrEP2))))))
    df_h<-as_long_data_frame(h)
    colnames(df_h)<-c("from","to","color1","color2")
    #Compute P(HIV|PrEP)
    treat_h<-subset(df_h, (df_h$color1=="blue"|df_h$color2=="blue"))
    treat_inf_contact_h<-subset(treat_h, treat_h$color1=="red"|treat_h$color2=="red")
    hiv_given_prep_h<-ifelse(nrow(treat_h)!=0,(nrow(treat_inf_contact_h)*p2)/nrow(treat_h),0)
    #Compute P(HIV|-PrEP)
    no_treat_h<-subset(df_h, df_h$color1!="blue"&df_h$color2!="blue")
    no_treat_inf_contact_h<-subset(no_treat_h, no_treat_h$color1=="red"|no_treat_h$color2=="red")
    hiv_given_no_prep_h<-ifelse(nrow(no_treat_h)!=0,(nrow(no_treat_inf_contact_h)*p1)/nrow(no_treat_h),0)
    #duplicate network structure, additional 10% treated 
    j<-set_vertex_attr(g,"color",value=c(rep("red", gorder(g)*phiv), rep("blue",gorder(g)*PrEP2), rep("black", gorder(g)*(1-(phiv+PrEP2)))))
    df_j<-as_long_data_frame(j)
    colnames(df_j)<-c("from","to","color1","color2")
    #compute (HIV|PrEP)
    treat_j<-subset(df_j, (df_j$color1=="blue"|df_j$color2=="blue"))
    treat_inf_contact_j<-subset(treat_j, treat_j$color1=="red"|treat_j$color2=="red")
    hiv_given_prep_j<-ifelse(nrow(treat_j)!=0,(nrow(treat_inf_contact_j)*p2)/nrow(treat_j),0)
    #Compute P(HIV|-PrEP)
    no_treat_j<-subset(df_j, df_j$color1!="blue"&df_j$color2!="blue")
    no_treat_inf_contact_j<-subset(no_treat_j, no_treat_j$color1=="red"|no_treat_j$color2=="red")
    hiv_given_no_prep_j<-ifelse(nrow(no_treat_j)!=0,(nrow(no_treat_inf_contact_j)*p1)/nrow(no_treat_j),0)
    # plot a random graph, 3 color options
    k <- sample_gnp(N,eprob)
    vertex_attr(k) <- list(color =c(rep("red", gorder(k)*phiv), rep("blue",gorder(k)*PrEP1), rep("black", gorder(k)*(1-(phiv+PrEP1)))))
    df_k<-as_long_data_frame(k)
    colnames(df_k)<-c("from","to","color1","color2")
    #Compute P(HIV|PrEP)
    treat_k<-subset(df_k, (df_k$color1=="blue"|df_k$color2=="blue"))
    treat_inf_contact_k<-subset(treat_k, treat_k$color1=="red"|treat_k$color2=="red")
    hiv_given_prep_k<-ifelse(nrow(treat_k)!=0,(nrow(treat_inf_contact_k)*p2)/nrow(treat_k),0)
    #Compute P(HIV|-PrEP)
    no_treat_k<-subset(df_k, df_k$color1!="blue"&df_k$color2!="blue")
    no_treat_inf_contact_k<-subset(no_treat_k, no_treat_k$color1=="red"|no_treat_k$color2=="red")
    hiv_given_no_prep_k<-ifelse(nrow(no_treat_k)!=0,(nrow(no_treat_inf_contact_k)*p1)/nrow(no_treat_k),0)
    # Combine effect estimates
    prep<-c(hiv_given_prep_g,hiv_given_prep_h,hiv_given_prep_j,hiv_given_prep_k)
    no_prep<-c(hiv_given_no_prep_g,hiv_given_no_prep_h,hiv_given_no_prep_j,hiv_given_no_prep_k)
    ef<-prep+no_prep
    names(ef)<-c("control,",paste("ran", PrEP2*100, sep=""),paste("ran", PrEP1*100,"+",PrEP1*100, sep=""),"regen")
    cc<-ef[-1]-ef[1]
    names(cc)<-c(paste("ran", PrEP2*100, sep=""),paste("ran", PrEP1*100,"+",PrEP1*100, sep=""),"regen")
    return(cc)}}