---
title: "simtest"
output: html_document
date: "2023-04-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
```

```{r libraries}
require(igraph)
```

```{r params}
N <- 1000 #network population/ graph order
model = "BA"
eprob <- 3/N #edge formation probability for ER model
pow <- 1 #preferential attachment power for BA model
nb <- 5 # neighborhood parameter for small-world model
rprob <- 3/N #rewiring probability for small-world model
phiv <- 0.1 # underlying hiv prevalence
PrEP1 <- 0.2 # PrEP assignment coverage in control treatment (a)
PrEP2 <-
  0.4 # PrEP assignment coverage in counterfactual treatment (a*)
#HIV risk by contact and PrEP allocation
p1 <- 0.2 #P(HIV|Contact and -PrEP)
p2 <- 0.1 #P(HIV|Contact and PrEP)
nsim <- 200
plots = T
set.seed(1000)
```


```{r control}
g <-
      if (model == "ER") {
        sample_gnp(N, eprob)
      } else if (model == "BA") {
        sample_pa(N, power = pow, directed = FALSE)
      } else if (model == "WS") {
        sample_smallworld(
          dim = 1,
          size = N,
          nei = nb,
          p = rprob
        )
      }
```

```{r control plot}
print(l_hiv_g <- round((gorder(g) * phiv), 0))
print(l_PrEP1_g <- round(((gorder(
  g
) - l_hiv_g) * PrEP1), 0))
print(l_sus_g <- round((gorder(g) - (l_hiv_g + l_PrEP1_g)), 0))
print(vertex_attr(g) <-
  list(color = c(
    rep("red", l_hiv_g),
    rep("blue", l_PrEP1_g),
    rep("black", l_sus_g)
  )))

if (plots) {
  coords = layout_nicely(g)
  plot(
    g,
    vertex.size = 10,
    # vertex.label.cex = 1,
    # vertex.label.dist = 2,
    vertex.label=NA,
    main = "Control",
    layout = coords
  )
}
    ```
    
    ```{r control risks}
   print( inf_contact_g <-
      setdiff(unlist(adjacent_vertices(g, v = V(g)[color == "red"])), V(g)[color ==
                                                                             "red"]))
    #compute P(HIV|PrEP)
    
print(treat_g <- V(g)[V(g)$color == "blue"])

print(    treat_inf_contact_g <-
      V(g)[inf_contact_g][which(V(g)[inf_contact_g]$color == "blue")])
    g <-
      set_vertex_attr(g,
                      name = "color",
                      index = inf_contact_g,
                      value = "orange")
    g <-
      set_vertex_attr(g,
                      name = "color",
                      index = treat_inf_contact_g,
                      value = "purple")
    if (plots) {
      plot(
        g,
        vertex.size = 10,
        vertex.label=NA,
        # vertex.label.cex = 1,
        # vertex.label.dist = 2,
        main = "Control",
        layout = coords
      )
    }
    print(hiv_given_prep_g <-
      ifelse(length(treat_g) != 0, (length(treat_inf_contact_g) * p2) / length(treat_g), 0))
    #Compute P(HIV|-PrEP)
    print(no_treat_g <- V(g)[V(g)$color %in% c("black", "orange")])
    no_treat_inf_contact_g <- V(g)[V(g)$color == "orange"]
    print(hiv_given_no_prep_g <-
      ifelse(length(no_treat_g) != 0, (length(no_treat_inf_contact_g) * p1) /
               length(no_treat_g), 0))
    ```
    
    ```{r random}
    #Randomly assign PrEP2% overall (shuffle attributes)
    l_hiv_h <- round((gorder(g) * phiv), 0)
    l_PrEP2_h <- round(((gorder(g) - l_hiv_h) * PrEP2), 0)
    l_sus_h <- round((gorder(g) - (l_hiv_h + l_PrEP2_h)), 0)
    h <-
      set_vertex_attr(g, "color", value = c(rep("red", l_hiv_h), sample(c(
        rep("blue", l_PrEP2_h), rep("black", l_sus_h)
      ))))
    if (plots) {
      plot(
        h,
        vertex.size = 10,
        vertex.label.cex = 1,
        vertex.label.dist = 2,
        main = "Random overall",
        layout = coords
      )
    }
    inf_contact_h <-
      setdiff(unlist(adjacent_vertices(h, v = V(h)[color == "red"])), V(h)[color ==
                                                                             "red"])
    #Compute P(HIV|PrEP)
    treat_h <- V(h)[V(h)$color == "blue"]
    treat_inf_contact_h <-
      V(h)[inf_contact_h][which(V(h)[inf_contact_h]$color == "blue")]
    h <-
      set_vertex_attr(h,
                      name = "color",
                      index = inf_contact_h,
                      value = "orange")
    h <-
      set_vertex_attr(h,
                      name = "color",
                      index = treat_inf_contact_h,
                      value = "purple")
    if (plots) {
      plot(
        h,
        vertex.size = 10,
        vertex.label.cex = 1,
        vertex.label.dist = 2,
        main = "Random overall",
        layout = coords
      )
    }
    print(hiv_given_prep_h <-
      ifelse(length(treat_h) != 0, (length(treat_inf_contact_h) * p2) / length(treat_h), 0))
    #Compute P(HIV|-PrEP)
    no_treat_h <- V(h)[V(h)$color %in% c("black", "orange")]
    no_treat_inf_contact_h <- V(h)[V(h)$color == "orange"]
    print(hiv_given_no_prep_h <-
      ifelse(length(no_treat_h) != 0, (length(no_treat_inf_contact_h) * p1) /
               length(no_treat_h), 0))
    ```
    
    ```{r additive}
    
    #duplicate network structure, additional PrEP2-PrEP1% treated
    l_hiv_j <- round((gorder(g) * phiv), 0)
    l_PrEP2_j <- round(((gorder(g) - l_hiv_j) * PrEP2), 0)
    l_sus_j <- round((gorder(g) - (l_hiv_j + l_PrEP2_j)), 0)
    j <-
      set_vertex_attr(g, "color", value = c(
        rep("red", l_hiv_j),
        rep("blue", l_PrEP2_j),
        rep("black", l_sus_j)
      ))
    if (plots) {
      plot(
        j,
        vertex.size = 10,
        vertex.label.cex = 1,
        vertex.label.dist = 2,
        main = "Random additional",
        layout = coords
      )
    }
    inf_contact_j <-
      setdiff(unlist(adjacent_vertices(j, v = V(j)[color == "red"])), V(j)[color ==
                                                                             "red"])
    #compute (HIV|PrEP)
    print(treat_j <- V(j)[V(j)$color == "blue"])
    print(treat_inf_contact_j <-
      V(j)[inf_contact_j][which(V(j)[inf_contact_j]$color == "blue")])
    j <-
      set_vertex_attr(j,
                      name = "color",
                      index = inf_contact_j,
                      value = "orange")
    j <-
      set_vertex_attr(j,
                      name = "color",
                      index = treat_inf_contact_j,
                      value = "purple")
    if (plots) {
      plot(
        j,
        vertex.size = 10,
        vertex.label.cex = 1,
        vertex.label.dist = 2,
        main = "Random additional",
        layout = coords
      )
    }
    print(hiv_given_prep_j <-
      ifelse(length(treat_j) != 0, (length(treat_inf_contact_j) * p2) / length(treat_j), 0))
    #Compute P(HIV|-PrEP)
    no_treat_j <- V(j)[V(j)$color %in% c("black", "orange")]
    no_treat_inf_contact_j <- V(j)[V(j)$color == "orange"]
    print(hiv_given_no_prep_j <-
      ifelse(length(no_treat_j) != 0, (length(no_treat_inf_contact_j) * p1) /
               length(no_treat_j), 0))
    ```
    
    ```{r regenerated}
    # Regenerated graph
    k <-
      if (model == "ER") {
        sample_gnp(N, eprob)
      } else if (model == "BA") {
        sample_pa(N, power = pow, directed = FALSE)
      } else if (model == "WS") {
        sample_smallworld(
          dim = 1,
          size = N,
          nei = nb,
          p = rprob
        )
      }
    l_hiv_k <- round((gorder(k) * phiv), 0)
    l_PrEP2_k <- round(((gorder(k) - l_hiv_k) * PrEP2), 0)
    l_sus_k <- round((gorder(k) - (l_hiv_k + l_PrEP2_k)), 0)
    vertex_attr(k) <-
      list(color = c(
        rep("red", l_hiv_k),
        rep("blue", l_PrEP2_k),
        rep("black", l_sus_k)
      ))
    if (plots) {
      plot(
        k,
        vertex.size = 10,
        vertex.label.cex = 1,
        vertex.label.dist = 2,
        main = "Regenerated",
        layout = coords
      )
    }
    inf_contact_k <-
      setdiff(unlist(adjacent_vertices(k, v = V(k)[color == "red"])), V(k)[color ==
                                                                             "red"])
    #Compute P(HIV|PrEP)
    treat_k <- V(k)[V(k)$color == "blue"]
    treat_inf_contact_k <-
      V(k)[inf_contact_k][which(V(k)[inf_contact_k]$color == "blue")]
    k <-
      set_vertex_attr(k,
                      name = "color",
                      index = inf_contact_k,
                      value = "orange")
    k <-
      set_vertex_attr(k,
                      name = "color",
                      index = treat_inf_contact_k,
                      value = "purple")
    if (plots) {
      plot(
        k,
        vertex.size = 10,
        vertex.label.cex = 1,
        vertex.label.dist = 2,
        main = "Regenerated",
        layout = coords
      )
    }
  print(hiv_given_prep_k <-
      ifelse(length(treat_k) != 0, (length(treat_inf_contact_k) * p2) / length(treat_k), 0))
    #Compute P(HIV|-PrEP)
    no_treat_k <- V(k)[V(k)$color %in% c("black", "orange")]
    no_treat_inf_contact_k <- V(k)[V(k)$color == "orange"]
    print(hiv_given_no_prep_k <-
      ifelse(length(no_treat_k) != 0, (length(no_treat_inf_contact_k) * p1) /
               length(no_treat_k), 0))
```

```{r risks}
  # Combine risk estimates
    prep <-
      c(hiv_given_prep_g,
        hiv_given_prep_h,
        hiv_given_prep_j,
        hiv_given_prep_k)
    names(prep) <-
      c("hiv_given_prep_g",
        "hiv_given_prep_h",
        "hiv_given_prep_j",
        "hiv_given_prep_k")
    
    print(prep)
    
    no_prep <-
      c(
        hiv_given_no_prep_g,
        hiv_given_no_prep_h,
        hiv_given_no_prep_j,
        hiv_given_no_prep_k
      )
    names(no_prep) <-
      c(
        "hiv_given_no_prep_g",
        "hiv_given_no_prep_h",
        "hiv_given_no_prep_j",
        "hiv_given_no_prep_k"
      )
    
    print(no_prep)
    
    ef <- prep + no_prep
    names(ef) <- c("control,", "random", "additive", "regenerated")
    
print(ef)
```

```{r contrasts}
 #compute causal contrasts
    cc <- as.data.frame(t(ef[-1] - ef[1]))
    names(cc) <- c("random", "additive", "regenerated")
    print(cc)
    
```

```{r output}

```

