---
title: "Multilayer Network Visualization"
output: html_document
date: '2022-10-09'
---

```{r libs}
require(igraph)
require(multinet)
require(EpiModel)
require(tidyverse)
require(ggraph)
```

```{r params}
N<-50 #network population/ graph order
model="ER"
eprob<-0.1 #edge formation probability for ER model 
pow<-1 #preferential attachment power for BA model
nb<-20 # neighborhood parameter for small-world model
rprob<-0.05 #rewiring probability for small-world model
phiv<-0.1 # underlying hiv prevalence
PrEP1<-0.2 # PrEP assignment coverage in control treatment (a) 
PrEP2<-0.4 # PrEP assignment coverage in counterfactual treatment (a*)
#HIV risk by contact and PrEP allocation 
p1<-0.2 #P(HIV|Contact and -PrEP)
p2<-0.1 #P(HIV|Contact and PrEP)
```

## Generate networks to be made into layers
```{r function}
sim_multi<-function(N=20,phiv=0.1,PrEP1=0.1,PrEP2=0.2, p1=0.2,p2=0.1,model=c("ER","BA","WS"),eprob=0.1,pow=1,nb=5,rprob=0.05){
   #parameter check
model<-match.arg(model)
# plot a random graph, 3 color options
#control scenario graph, 10% assignment prob
g<-if(model=="ER"){sample_gnp(N,eprob)} else if(model=="BA"){sample_pa(N,power=pow,directed=FALSE)} else if(model=="WS"){sample_smallworld(dim=1,size=N,nei=nb,p=rprob)}
l_hiv_g<-round((gorder(g)*phiv),0)
l_PrEP1_g<-round(((gorder(g)-l_hiv_g)*PrEP1),0)
l_sus_g<-round((gorder(g)-(l_hiv_g+l_PrEP1_g)),0)
vertex_attr(g) <- list(color=c(rep("red", l_hiv_g), rep("blue",l_PrEP1_g), rep("black",l_sus_g)))
inf_contact_g<-setdiff(unlist(adjacent_vertices(g,v=V(g)[color=="red"])), V(g)[color=="red"])
#Label infectious contacts
treat_g<-V(g)[V(g)$color=="blue"]
treat_inf_contact_g<- V(g)[inf_contact_g][which(V(g)[inf_contact_g]$color=="blue")]
g<-set_vertex_attr(g,name="color",index=inf_contact_g,value="orange")
g<-set_vertex_attr(g, name="color",index=treat_inf_contact_g,value="purple")
#Randomly assign 20% overall (shuffle attributes)
l_hiv_h<-round((gorder(g)*phiv),0)
l_PrEP2_h<-round(((gorder(g)-l_hiv_h)*PrEP2),0)
l_sus_h<-round((gorder(g)-(l_hiv_h+l_PrEP2_h)),0)
h<-set_vertex_attr(g,"color",value=c(rep("red",l_hiv_h), sample(c(rep("blue",l_PrEP2_h), rep("black", l_sus_h)))))
inf_contact_h<-setdiff(unlist(adjacent_vertices(h,v=V(h)[color=="red"])), V(h)[color=="red"])
treat_h<-V(h)[V(h)$color=="blue"]
treat_inf_contact_h<-V(h)[inf_contact_h][which(V(h)[inf_contact_h]$color=="blue")]
h<-set_vertex_attr(h,name="color",index=inf_contact_h,value="orange")
h<-set_vertex_attr(h, name="color",index=treat_inf_contact_h,value="purple")
#duplicate network structure, additional 10% treated
l_hiv_j<-round((gorder(g)*phiv),0)
l_PrEP2_j<-round(((gorder(g)-l_hiv_j)*PrEP2),0)
l_sus_j<-round((gorder(g)-(l_hiv_j+l_PrEP2_j)),0)
j<-set_vertex_attr(g,"color",value=c(rep("red", l_hiv_j), rep("blue",l_PrEP2_j), rep("black", l_sus_j)))
inf_contact_j<-setdiff(unlist(adjacent_vertices(j,v=V(j)[color=="red"])), V(j)[color=="red"])
treat_j<-V(j)[V(j)$color=="blue"]
treat_inf_contact_j<-V(j)[inf_contact_j][which(V(j)[inf_contact_j]$color=="blue")]
j<-set_vertex_attr(j,name="color",index=inf_contact_j,value="orange")
j<-set_vertex_attr(j, name="color",index=treat_inf_contact_j,value="purple")
# plot a random graph, 3 color options
k <- if(model=="ER"){sample_gnp(N,eprob)} else if(model=="BA"){sample_pa(N,power=pow,directed=FALSE)} else if(model=="WS"){sample_smallworld(dim=1,size=N,nei=nb,p=rprob)}
l_hiv_k<-round((gorder(k)*phiv),0)
l_PrEP2_k<-round(((gorder(k)-l_hiv_k)*PrEP2),0)
l_sus_k<-round((gorder(k)-(l_hiv_k+l_PrEP2_k)),0)
vertex_attr(k) <- list(color =c(rep("red", l_hiv_k), rep("blue",l_PrEP2_k), rep("black", l_sus_k)))
inf_contact_k<-setdiff(unlist(adjacent_vertices(k,v=V(k)[color=="red"])), V(k)[color=="red"])
#Compute P(HIV|PrEP)
treat_k<-V(k)[V(k)$color=="blue"]
treat_inf_contact_k<-V(k)[inf_contact_k][which(V(k)[inf_contact_k]$color=="blue")]
k<-set_vertex_attr(k,name="color",index=inf_contact_k,value="orange")
k<-set_vertex_attr(k, name="color",index=treat_inf_contact_k,value="purple")
#Compute P(HIV|-PrEP)
no_treat_k<-V(k)[V(k)$color%in% c("black","orange")]
no_treat_inf_contact_k<-V(h)[V(h)$color=="orange"]
#Network Summary Statistics
stats_g<-c(
Co_g<-count_components(g), #Number of Components
Cs_g<-max(components(g)$csize),#Largest Component Size
B_g<-mean(betweenness(g)),# Average Betweenness Centrality
De_g<-edge_density(g),#Density
Ce_g<-centr_degree(g)$centralization,#Degree Centralization
G_g<-mean_distance(g),#Average geodesic distance
Di_g<-diameter(g),#Network Diameter
T_g<-transitivity(g),#Transitivity/Clustering
K_g<-sum(coreness(g)==2)/length(coreness(g)),#Proportion of nodes in 2-cores
As_g<-assortativity_degree(g,directed=F) #Degree Assortativity
)
names(stats_g)<-c("Number of Components g","Largest Component Size g", "Avg. Betweenness g","Density g","Degree Centralization g","Avg. Geodesic Distance g", "Diameter g", "Transitivity g","Proportion of nodes in 2-cores g", "Degree Assortativity g")
stats_k<-c(
Co_k<-count_components(k), #Number of Components
Cs_k<-max(components(k)$csize),#Largest Component Size
B_k<-mean(betweenness(k)),# Average Betweenness Centrality
De_k<-edge_density(k),#Density
Ce_k<-centr_degree(k)$centralization,#Degree Centralization
G_k<-mean_distance(k),#Average geodesic distance
Di_k<-diameter(k),#Network Diameter
T_k<-transitivity(k),#Transitivity/Clustering
K_k<-sum(coreness(k)==2)/length(coreness(k)),#Proportion of nodes in 2-cores,
As_k<-assortativity_degree(k,directed=F) #Degree Assortativity
)
names(stats_k)<-c("Number of Components k","Largest Component Size k", "Avg. Betweenness k","Density k","Degree Centralization k","Avg. Geodesic Distance k", "Diameter k", "Transitivity k","Proportion of nodes in 2-cores k", "Degree Assortativity k")
output<-list(g,h,j,k,as.data.frame(t(stats_g)),as.data.frame(t(stats_k)))
return(output)
}
```

```{r multinet}
res_multi<-sim_multi(N=N, model=model)
g<-res_multi[[1]]
g<-set_vertex_attr(g,"name",value=seq(1,gorder(g)))
h<-res_multi[[2]]
h<-set_vertex_attr(h,"name",value=seq(1,gorder(h)))
j<-res_multi[[3]]
j<-set_vertex_attr(j,"name",value=seq(1,gorder(j)))
k<-res_multi[[4]]
k<-set_vertex_attr(k,"name",value=seq(1,gorder(k)))
n<-ml_empty()
add_igraph_layer_ml(n,g,"control")
add_igraph_layer_ml(n,h,"ran")
add_igraph_layer_ml(n,j,"add")
add_igraph_layer_ml(n,k,"regen")
colors<-get_values_ml(n, "color", vertices=vertices_ml(n,layers=c("control","ran","add","regen")))
pcols<-gplots::col2hex(t(colors))
plot(n,vertex.color = pcols,vertex.labels = "")
# legend("bottom",legend=c("HIV+","PrEP+ Contact-","PrEP+ Contact+","PrEP- Contact-","PrEP- Contact+"),col=unique(pcols))
```

```{r}
hist(degree_ml(n))
```



